#!/bin/bash

if [[ -d ~/.config/omarchy/hooks/theme-set.conf ]]; then
  for hook in ~/.config/omarchy/hooks/theme-set.conf/*.sh; do
    if [[ -f "$hook" && -x "$hook" ]]; then
      if ! "$hook"; then
          printf "[ERROR]: Hook $(basename "$hook") failed!\n" >&2
      fi
    fi
  done
fi
