#!/bin/bash
#
error() {
    echo -e "\e[31m[ERROR]\e[0m $1"
    exit 1
}

# execute core omarchy recipe recipes
if [[ -d /etc/omarchy/recipes.d ]]; then
  for recipe in /etc/omarchy/recipes.d/*.sh; do
    if [[ -f "$recipe" && -x "$recipe" ]]; then
      if ! "$recipe"; then
          error "$(basename "$recipe") failed!" >&2
      fi
    fi
  done
fi

# execute user recipe recipes
if [[ -d $HOME/.config/omarchy/recipes.d/ ]]; then
  for recipe in $HOME/.config/omarchy/recipes.d/*.sh; do
    if [[ -f "$recipe" && -x "$recipe" ]]; then
      if ! "$recipe"; then
          error "$(basename "$recipe") failed!" >&2
      fi
    fi
  done
fi
