#!/bin/bash
#
error() {
    echo -e "\e[31m[ERROR]\e[0m $1"
    exit 1
}

if [[ -d ./recipes.d ]]; then
  for hook in ./recipes.d/*.sh; do
    if [[ -f "$hook" && -x "$hook" ]]; then
      if ! "$hook"; then
          error "$(basename "$hook") failed!" >&2
      fi
    fi
  done
fi
