#!/bin/bash

if ! command -v cava >/dev/null 2>&1; then
    skipped "Cava"
fi

output_file="$HOME/.config/omarchy/current/theme/cava.conf"

if [ ! -f "$output_file" ]; then
    cat > "$output_file" << EOF
## Configuration file for Cava.
## Theme-aware gradient generated by Omarchy

[general]

[input]

[output]

[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '#${normal_cyan:-${primary_foreground}}'
gradient_color_2 = '#${normal_blue:-${primary_foreground}}'
gradient_color_3 = '#${bright_blue:-${normal_blue:-${primary_foreground}}}'
gradient_color_4 = '#${normal_magenta:-${primary_foreground}}'
gradient_color_5 = '#${bright_magenta:-${normal_magenta:-${primary_foreground}}}'
gradient_color_6 = '#${bright_cyan:-${normal_cyan:-${primary_foreground}}}'
gradient_color_7 = '#${bright_magenta:-${normal_magenta:-${primary_foreground}}}'
gradient_color_8 = '#${normal_cyan:-${primary_foreground}}'

[smoothing]

[eq]
EOF
fi

mkdir -p "$HOME/.config/cava"
cp -f "$output_file" "$HOME/.config/cava/config"

if pgrep -x cava >/dev/null 2>&1; then
    ( pkill -USR2 cava ) >/dev/null 2>&1 &
fi

success "Cava theme updated!"
exit 0
